### ISSUE TITLE
Cannot install Mango via Pear. Also does not run on Apple.

### ISSUE THREAD

**Issue by shlomi-noach** [dcramer/mangodb#39]

**Comment by philovivero** [comment]
Perhaps your Apple just isn't webscale enough? It's not surprising a sluggish, slow 1990's era package manager can't keep up with the blazing speed of Mango. Trying to install Mango via Pear would be like trying to race a Tesla in a baby bumper car arena.

Only MangoDB is truly web-scale, which means you need to use web-scale tools to work with it.

**Comment by shlomi-noach** [comment]
It's sad I need to read this comment through the Grapevine :(
